export default {
  ADD_PRODUCT_REQUEST: 'PRODUCTS_ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS: 'PRODUCTS_ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE: 'PRODUCTS_ADD_PRODUCT_FAILURE',
  GET_PRODUCTS_REQUEST: 'PRODUCTS_GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS: 'PRODUCTS_GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: 'PRODUCTS_GET_PRODUCTS_FAILURE',
  EDIT_PRODUCT_REQUEST: 'PRODUCTS_EDIT_PRODUCT_REQUEST',
  EDIT_PRODUCT_SUCCESS: 'PRODUCTS_EDIT_PRODUCT_SUCCESS',
  EDIT_PRODUCT_FAILURE: 'PRODUCTS_EDIT_PRODUCT_FAILURE',
};